# Generated by Django 3.1.3 on 2022-01-01 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedulename', models.CharField(max_length=25, null=True)),
                ('eventtype', models.CharField(max_length=30, null=True)),
                ('scheduledate', models.CharField(max_length=30, null=True)),
                ('scheduletimefrom', models.CharField(max_length=30, null=True)),
                ('scheduletimeto', models.CharField(max_length=30, null=True)),
                ('scheduledDes', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
