# Generated by Django 3.1.3 on 2022-01-01 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women', '0003_auto_20220101_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vmother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.CharField(max_length=5, null=True)),
                ('vmname', models.CharField(max_length=30, null=True)),
                ('vmdur', models.CharField(max_length=30, null=True)),
                ('vmdis', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vbaby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=5, null=True)),
                ('vname', models.CharField(max_length=30, null=True)),
                ('vdur', models.CharField(max_length=30, null=True)),
                ('vdose', models.CharField(max_length=30, null=True)),
                ('vroute', models.CharField(max_length=30, null=True)),
                ('vsite', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
