# Generated by Django 3.1.3 on 2022-01-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_auto_20220102_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditation',
            name='image',
        ),
        migrations.AddField(
            model_name='meditation',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
