# Generated by Django 3.1.3 on 2022-01-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_auto_20220102_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meditation',
            old_name='video',
            new_name='video1',
        ),
    ]
